### ISSUE TITLE
Doxygen dot not found errors

### ISSUE THREAD

**Issue by y4my4my4m** [klaussilveira/qengine#4]
I would receive this error upon `cmake ..`

```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Doxygen (missing: dot) (found version "1.8.14")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindDoxygen.cmake:615 (find_package_handle_standard_args)
  CMakeLists.txt:289 (find_package)
```

I've resolved it by installing `graphviz` and was able to compile.
Thought this info might help others.

---
Running Manjaro Linux

**Comment by klaussilveira** [comment]
If you don't want to build the docs, or you don't want to install the deps they require, you can pass `-DBUILD_DOCS=OFF` to `cmake`. The `README` should be updated with this. Thanks!
